### ISSUE TITLE
styles omitted when `calc` expressions contain parenthesized expressions with variables

### ISSUE THREAD

**Issue by Enteleform** [vivliostyle/vivliostyle.js#1014]
## Describe the bug
If a calculated style contains variables inside of parenthesized expressions, the definition is omitted from the rendered stylesheet. It is possible to work around this issue by prefixing these parenthesized expressions with an explicit `calc`.

In this example, all `.Text` styles should be the same, but the one for `.Text.Implicit.Variable` demonstrates the described issue. The non-vivliostyle-rendered DOM on the left demonstrates the expected output.

![image](https://user-images.githubusercontent.com/10906415/193715743-823a33ca-2b43-4c30-9cd0-048c86f3325d.png)

## Expected behavior
Style definitions with parenthesized expressions containing variables are rendered without the need for explicit `calc` prefixes.

## To Reproduce
[github.com/enteleform-codesandbox/0020--Vivliostyle--CalculatedStyles](https://github.com/enteleform-codesandbox/0020--Vivliostyle--CalculatedStyles)

## Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.91

**Comment by MurakamiShinyu** [comment]
Fixed in #1021 

Test: https://vivliostyle-git-fix-issue1014-vivliostyle.vercel.app/#src=https://raw.githack.com/enteleform-codesandbox/0020--Vivliostyle--CalculatedStyles/main/index.html

![Screen Shot 2022-10-11 at 22 34 08](https://user-images.githubusercontent.com/3324737/195105428-bd18fba4-243d-4400-919a-5f48660c0d49.png)
