### ISSUE TITLE
variable hoisting to `element.style` breaks scoping for variables with the same name

### ISSUE THREAD

**Issue by Enteleform** [vivliostyle/vivliostyle.js#1015]
## Describe the bug
Vivliostyle's hoisting of variables to `element.style` breaks scoping for variables with the same name by introducing recursive references that did not exist prior to the restructuring of the stylesheet.

In this example, both `.Text` styles should be the same, but the one for `.Text.InnerScope` is broken due to the recursive reference. The non-vivliostyle-rendered DOM on the left demonstrates the expected output.

![dom-comparison](https://user-images.githubusercontent.com/10906415/193713348-f2def765-a74c-4bc0-9580-064704944161.png)

https://user-images.githubusercontent.com/10906415/193713671-0c1b09ed-d904-41be-8423-cf96fdbe43d7.mp4

## Expected behavior
CSS variable scopes are preserved.

## To Reproduce
[github.com/enteleform-codesandbox/0019--Vivliostyle--VariableResolution](https://github.com/enteleform-codesandbox/0019--Vivliostyle--VariableResolution)

## Desktop
 - OS: Windows 10
 - Browser: Chrome
 - Version: 106.0.5249.91

**Comment by MurakamiShinyu** [comment]
@Enteleform Thanks for finding the bug!

Fixed in #1018.

Test: https://vivliostyle-git-fix-issue1015-vivliostyle.vercel.app/#src=https://raw.githack.com/enteleform-codesandbox/0019--Vivliostyle--VariableResolution/main/index.html

Result:
![Screen Shot 2022-10-07 at 2 00 55](https://user-images.githubusercontent.com/3324737/194374548-dab2266e-ba09-4bcc-bc7c-9dfdc91d3459.png)
