### ISSUE TITLE
Problem on box edge treatment at page break (罫囲み文字の表示崩れ)

### ISSUE THREAD

**Issue by skmtjny** [vivliostyle/vivliostyle.js#1030]
**Describe the bug**

罫線を設定したspanがページまたは段をまたぐ場合、以下の現象が発生しました。

 - 現象1：文字がない位置に罫線が表示される
 - 現象2：次ページ、開始位置の罫線が閉じてしまう

**Screenshots**
![screen_shot](https://user-images.githubusercontent.com/1134887/199170791-e980c8a3-eb27-4189-aef8-0928d91c5ce1.png)
 
**To Reproduce**
 - 添付ファイルを解凍し、vivliostyle/cliでhtmlを読み込み

**Expected behavior**
![Expected_behavior](https://user-images.githubusercontent.com/1134887/199170845-18e04f7e-3594-43bf-ab3a-1b54fbaf2513.png)

**Desktop**
 - OS: Windows 10 64 bit
 - Browser: Chromium 107.0.5304.18（Developer Build） （64 ビット）
 - cli: 5.8.1
 - core: 2.19.1

**Additional context**
 - previewおよびbuild（PDF）で同様の状態になっていることを確認
 - 縦組み、横組み、それぞれの段末、頁末でこの現象が発生することを確認

どうぞよろしくお願いいたします。

[report_221101.zip](https://github.com/vivliostyle/vivliostyle.js/files/9907396/report_221101.zip)

**Comment by MurakamiShinyu** [comment]
Vivliostyle.jsでの段・ページ分割処理で起きる問題です。
改善する方法がないか検討します。

**Comment by MurakamiShinyu** [comment]
I made more test sample files in my GitHub repo: https://github.com/MurakamiShinyu/bugtest/tree/main/box-break/

**Comment by MurakamiShinyu** [comment]
- Fixed in #1037.

## Test

> I made more test sample files in my GitHub repo: https://github.com/MurakamiShinyu/bugtest/tree/main/box-break/


Compare before and after this fix.

- [pbreak-inline.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline.html
- [pbreak-inline-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-justify.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-justify.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-justify.html
- [pbreak-inline-nest.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest.html
- [pbreak-inline-nest-vert.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-vert.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-vert.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-vert.html
- [pbreak-inline-nest-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify.html
- [pbreak-inline-nest-justify-vert.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify-vert.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify-vert.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-inline-nest-justify-vert.html
- [pbreak-block.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block.html
- [pbreak-block-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-justify.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-justify.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-justify.html
- [pbreak-block-nest.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest.html
- [pbreak-block-nest-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-justify.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-justify.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-justify.html
- [pbreak-block-nest-inline.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline.html
- [pbreak-block-nest-inline-clone.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-clone.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-clone.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-clone.html
- [pbreak-block-nest-inline-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html
- [pbreak-block-nest-inline-justify-vert.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-vert.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-vert.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-vert.html
- [pbreak-block-nest-inline-justify-clone.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html
- [pbreak-block-nest-inline-justify-clone-vert.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone-vert.html)
  - Test with Vivliostyle
    - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone-vert.html
    - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone-vert.html

### Some of result screenshots:

> - [pbreak-block-nest-inline-justify.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html)
>   - Test with Vivliostyle
>     - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html
>     - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify.html

![Screenshot 2022-11-12 at 17 52 59](https://user-images.githubusercontent.com/3324737/201466766-cbb0bf73-d552-4cd3-a88b-62a2e6510d3b.png) → Fixed: ![Screenshot 2022-11-12 at 17 53 34](https://user-images.githubusercontent.com/3324737/201466775-f31ecc3b-26a6-4357-a2cc-57c1b6fc187a.png)

> - [pbreak-block-nest-inline-justify-clone.html](https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html)
>   - Test with Vivliostyle
>     - Before this fix: https://vivliostyle.github.io/viewer/v2.19.1/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html
>     - After this fix: https://vivliostyle-git-fix-issue1030-vivliostyle.vercel.app/#src=https://github.com/MurakamiShinyu/bugtest/blob/main/box-break/pbreak-block-nest-inline-justify-clone.html

![Screenshot 2022-11-12 at 17 47 48](https://user-images.githubusercontent.com/3324737/201466629-3c06b369-2669-4035-8a61-f81fe646bc1f.png) → Fixed: ![Screenshot 2022-11-12 at 17 48 43](https://user-images.githubusercontent.com/3324737/201466636-64a29873-6808-499c-ac6f-d707375be145.png)

**Comment by MurakamiShinyu** [comment]
The result screenshot of the reported sample:

![Screenshot 2022-11-12 at 17 35 21](https://user-images.githubusercontent.com/3324737/201466177-395ce8d2-d607-4270-8c63-b5362faaba1e.png)
