### ISSUE TITLE
脚注関連の擬似要素にスタイルを指定した場合に番号つきリストのカウントがおかしくなる？ Numbered list counts go wrong when styles are specified for footnote-related pseudo-elements?

### ISSUE THREAD

**Issue by Stauboid** [vivliostyle/vivliostyle.js#1200]
**Describe the bug**
HTML側に`<ul>`を内側に含んだ`<ol>`があり、CSSに`::footnote-marker{ ... }`および`::footnote-call{ ... }`というブロックが存在する場合、`<ol>`の番号が正しく振られないように見えます。
If the HTML document has an `<ol>`  which in turn containing a `<ul>`, and the CSS has blocks `::footnote-marker{ ... }` and `::footnote-call{ ... }`, then `<ol>` doesn't seem to be numbered correctly.

**To Reproduce**

以下の内容のHTML書類とCSS書類を作成し、`vivliostyle preview hoge.html` あるいは `vivliostyle build hoge.html` でPDFを作成する。
Create HTML and CSS documents with the following contents and create a PDF with `vivliostyle preview hoge.html` or `vivliostyle build hoge.html`.

hoge.html:

```html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <title>test</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <ol>
      <li>item</li>
      <ul>
          <li>item</li>
      </ul>
      <li>item</li>
  </ol>
</body>
```

style.css:

```style.css
::footnote-marker {
}


::footnote-call {
}
```

<vivliostyle.org> の Vivliostyle Viewer で確認する場合、以下のURLで確認できます：
If you want to check it with Vivliostyle Viewer at <vivliostyle.org>, you can use the following URL:

https://vivliostyle.org/viewer/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22ja%22%3E%20%3Chead%3E%20%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%20%20%20%3Ctitle%3Etest%3C/title%3E%20%20%20%3Clink%20rel=%22stylesheet%22%20href=%22style.css%22%20/%3E%20%3C/head%3E%20%3Cbody%3E%20%20%20%3Col%3E%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%20%20%20%20%3Cul%3E%20%20%20%20%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%20%20%20%20%3C/ul%3E%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%3C/ol%3E%20%3C/body%3E&style=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0A%0A%0A::footnote-marker%20%7B%0A%7D%0A%0A%0A::footnote-call%20%7B%0A%7D

**Expected behavior**

```markdown
1. item
    - item
2. item
```

**actual behavior**

```
1. item
    - item
1. item
```

**Additional context**
vivliostyle cli の バージョン：
cli: 7.2.5
core: 2.24.3

**Comment by MurakamiShinyu** [comment]
@Stauboid バグ報告ありがとうございます。現象を確認しました。

バグ修正できるまでの回避策としては、脚注関連の擬似要素を使うときは脚注の要素（例 `<span class="footnote">`）にだけその擬似要素を指定するようにすることです。例：

```css
.footnote::footnote-marker {
  ...
}
.footnote::footnote-call {
  ...
}
```

**Comment by MurakamiShinyu** [comment]
Fixed in #1203.

Test:
https://vivliostyle-git-fix-issue1200-vivliostyle.vercel.app/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%20lang=%22ja%22%3E%20%3Chead%3E%20%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%20%20%20%3Ctitle%3Etest%3C/title%3E%20%20%20%3Clink%20rel=%22stylesheet%22%20href=%22style.css%22%20/%3E%20%3C/head%3E%20%3Cbody%3E%20%20%20%3Col%3E%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%20%20%20%20%3Cul%3E%20%20%20%20%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%20%20%20%20%3C/ul%3E%20%20%20%20%20%20%20%3Cli%3Eitem%3C/li%3E%20%20%20%3C/ol%3E%20%3C/body%3E&style=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0A%0A%0A::footnote-marker%20%7B%0A%7D%0A%0A%0A::footnote-call%20%7B%0A%7D

Screenshot:
![スクリーンショット 2023-07-11 15 21 06](https://github.com/vivliostyle/vivliostyle.js/assets/3324737/de3fb0c6-80c5-4de3-8a5e-36f30791e461)
