### ISSUE TITLE
target-counter leads to pagination to wrong named page

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1272]
**Describe the bug**
When using the target-counter feature in a table of contents, Vivliostyle assigns some pages to a wrong named page.

**To Reproduce**
- Paginate the attached example file "bug.html" with Vivliostyle. (Simply put it into the Vivliostyle Viewer)

**Expected behavior**
- The background of the first page (title page) should be white
- The background of the second and third page (preamble and table of contents) should be yellow (from the named page "preamble")
- The background of the remaining pages should be white.
Note: The HTML file is only an excerpt from a full manual, so the missing page numbers in the TOC are expected.

**Actual behavior**
- Additional pages get a yellow background from the "preamble" named page rule which is wrong.

**Additional Information**
If you edit the the html file and remove the target-counter from the css rule, pagination is correct.

[bug.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/14236778/bug.html.zip)

**Comment by MurakamiShinyu** [comment]
@depth42 Thanks for reporting the bug.

~~I found that this problem did not happen until v2.21.1 and has been present since v2.22.0.~~ Sorry I was wrong. The `leader()` was not available until v2.21.1 and the `content: leader('.') target-counter(attr(href), page)` was not evaluated, so the issue on target-counter did not happen. With the modified test [issue1272-bug-no-leader.html](https://gist.githubusercontent.com/MurakamiShinyu/e61b396e0a9947652124a5a5fb92a82d/raw/issue1272-bug-no-leader.html), I confirmed that the problem existed since v2.7.0 in which the named page feature was implemented: https://vivliostyle.github.io/viewer/v2.7.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/e61b396e0a9947652124a5a5fb92a82d/raw/issue1272-bug-no-leader.html

**Comment by MurakamiShinyu** [comment]
Fixed in #1274.

Test:
- Before the fix (v2.27.0): https://vivliostyle.github.io/viewer/v2.27.0/#src=https://gist.githubusercontent.com/MurakamiShinyu/e61b396e0a9947652124a5a5fb92a82d/raw/issue1272-bug.html
- After the fix: https://vivliostyle-git-fix-issue1272-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/e61b396e0a9947652124a5a5fb92a82d/raw/issue1272-bug.html

**Comment by depth42** [comment]
Thank you for fixing this! 
Is there a way I can build vivliostyle-print including this fix before you have made an official release?

**Comment by MurakamiShinyu** [comment]
> Is there a way I can build vivliostyle-print including this fix before you have made an official release?

Try the following steps:

```
git clone https://github.com/vivliostyle/vivliostyle.js
git clone https://github.com/vivliostyle/vivliostyle-print

# Build vivliostyle.js
cd vivliostyle.js
yarn install
yarn bootstrap
yarn build

# Link @vivliostyle/core to vivliostyle-print
cd packages/core
yarn link
cd ../../../vivliostyle-print
yarn link @vivliostyle/core

# Build vivliostyle-print
yarn install
yarn build_demo

# test the demo with http-server
http-server demo -o
```

**Comment by depth42** [comment]
Thank you for the instructions. Unfortunately, your script creates an error in the yarn install step of vivliostyle-print:

[!] Error: 'printHTML' is not exported by ../../../../Users/frank/test/vivliostyle.js/packages/core/lib/vivliostyle.js, imported by src/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.js (1:8)
1: export {printHTML} from "@vivliostyle/core"
           ^
Error: 'printHTML' is not exported by ../../../../Users/frank/test/vivliostyle.js/packages/core/lib/vivliostyle.js, imported by src/index.js
    at error (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:198:30)
    at Module.error (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:12560:16)
    at Module.getVariableForExportName (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:12715:29)
    at Module.includeAllExports (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:12787:37)
    at Graph.includeStatements (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:23159:36)
    at Graph.build (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:23074:14)
    at /private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:23768:13
    at catchUnfinishedHookActions (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:23247:20)
    at rollupInternal (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/shared/rollup.js:23765:5)
    at build (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/bin/rollup:1528:20)
    at runRollup (/private/tmp/vivliostyle/vivliostyle-print/node_modules/rollup/dist/bin/rollup:1668:21)

**Comment by MurakamiShinyu** [comment]
@depth42 Looking at your error log, it appears that `vivliostyle.js` and `vivliostyle-print` are placed in different directories (`/Users/frank/test/` and `/private/tmp/vivliostyle/`). Could you try it again in a same directory?

**Comment by depth42** [comment]
Thank you, now it is working. The build process must have somehow picked up a wrong version.
