### ISSUE TITLE
Missing background color when using variables and @media

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1313]
**Describe the bug**
Using a @media rule makes background color disappear in combination with using a CSS variable.

**To Reproduce**
Paginate the attached file "test.html" with Vivliostyle.

[test.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/15150074/test.html.zip)

**Expected behavior**
The box containing the text "test" should have a green background color. Instead it does not have a background color.

**Desktop (please complete the following information):**
 - macOS 14.4
 - Safari 17.4
 - 
**Additional context**
- When I remove the @media rule, the green background is shown. 
- When I replace the test variable in the @media rule with a literal color, the green background is shown.
- When opening test.html directly in Safari without pagination, the green background is shown.

**Comment by MurakamiShinyu** [comment]
@depth42 Thanks for reporting the bug! I will investigate the problem.

**Comment by MurakamiShinyu** [comment]
Fixed in #1315.

Test: (GitHub Gist: https://gist.github.com/MurakamiShinyu/1d1bdbb88903baf3617b14ad1cd5c09b )
- Before the fix (v2.18.1): https://vivliostyle.github.io/viewer/v2.28.1/#src=https://gist.githack.com/MurakamiShinyu/1d1bdbb88903baf3617b14ad1cd5c09b/raw/issue1313-test.html
- After the fix: https://vivliostyle-git-fix-issue1313-vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/1d1bdbb88903baf3617b14ad1cd5c09b/raw/issue1313-test.html
