### ISSUE TITLE
Missing image elements

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1383]
**Describe the bug**
Under some circumstances, image elements are missing in the paginated HTML output.

**To Reproduce**
Paginate the attached document with Vivliostyle v2.30.4

**Expected behavior**
The paginated output should contain an image at the bottom of the first page like in this screenshot.

<img width="1182" alt="expected" src="https://github.com/user-attachments/assets/1eee9a77-f10d-4919-ab1c-02b265fb5eb6">

**Actual behavior** 
The paginated output contains an empty area where the image should be:
<img width="1182" alt="actual" src="https://github.com/user-attachments/assets/85665955-e6df-4afe-a51f-0d74fb61f759">

**Desktop:**
 - macOS 15.0.1
 - Safari 18.0.1

**Additional context**
If you remove the span element (by removing lines 25 and 32 from the HTML input file), the pagination is working correctly.

[VivliostyleBug.zip](https://github.com/user-attachments/files/17306705/VivliostyleBug.zip)

**Comment by MurakamiShinyu** [comment]
@depth42 Thank you for reporting the issue. I am investigating it and found that this problem (float box near page bottom may disappear if the float element and its sibling elements have parent inline element) existed since very old versions of vivliostyle.

**Comment by MurakamiShinyu** [comment]
Fixed in PR #1384.

## Test

- [test1](https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test1.html)
  - Before Fix: https://vivliostyle.github.io/viewer/v2.30.4/#src=https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test1.html
  - After Fix: https://vivliostyle-git-fix-issue1383-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test1.html

- very simple case: [test4](https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test4.html)
  - Before Fix: https://vivliostyle.github.io/viewer/v2.30.4/#src=https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test4.html
  - After Fix: https://vivliostyle-git-fix-issue1383-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/8196f7c4954c4c698fe9c232c19ce3a0/raw/test4.html

**Comment by depth42** [comment]
Thank you for fixing this so fast. It now works fine.
