### ISSUE TITLE
CSS implicit list-item counter

### ISSUE THREAD

**Issue by yamahige** [vivliostyle/vivliostyle.js#1391]
**Is your feature request related to a problem? Please describe.**
I want to prepare an ordered list example with a large number digits. But, it seems that Vivliostyle does not support the implicit `list-item` counter.
[CSS Lists and Counters Module Level 3 - 4.6. The Implicit `list-item` Counter](https://www.w3.org/TR/css-lists-3/#valdef-counter-increment-list-item)

```
li {
    counter-increment: list-item 2;
}
```
```
<ol>
<li>NNNNN</li>
<li>NNNNN</li>
<li>NNNNN</li>
</ol>
```

Vivliostyle:
<https://vivliostyle.org/viewer/#src=https://gist.githubusercontent.com/yamahige/4e3e2bac575acc84fde84aeda5d711b9/raw/dcd73500606634a5aacf25ac8845852928a85b47/list-item-counter.html>
<img width="782" alt="Vivliostyle" src="https://github.com/user-attachments/assets/8c7a7e47-7b42-4f34-9fe6-8d1913f48461">

Chrome browser:
<img width="276" alt="chrome" src="https://github.com/user-attachments/assets/680a5065-2e2b-466c-8804-946264f85f23">

**Describe the solution you'd like**
Support the implicit built-in `list-item` counter

**Describe alternatives you've considered**
Use custom ordered list with explicit custom counter.

**Comment by MurakamiShinyu** [comment]
In the current implementation, Vivliostyle.js uses `ua-list-item` counter instead of `list-item`. I will change this and check if it works. 

https://github.com/vivliostyle/vivliostyle.js/blob/49970360cebec5e9b692c48b419a281c5edecf21/packages/core/src/vivliostyle/css-cascade.ts#L3049-L3071

https://github.com/vivliostyle/vivliostyle.js/blob/49970360cebec5e9b692c48b419a281c5edecf21/packages/core/src/vivliostyle/css-cascade.ts#L3130-L3137

**Comment by MurakamiShinyu** [comment]
I found that changing `ua-list-item` to `list-item` in the code does not solve the issue. The problem is not that simple.

CSS counter is implemented in Vivliostyle.js, not using browser's native CSS counter. However, Vivliostyle.js uses browser's native list style with `display: list-item` for list items, so the browser's native CSS counter is used for list items. This inconsistency causes the issue.

To solve this issue, Vivliostyle.js needs to rework the implementation of lists and counters. This is not a simple task.

Related feature requests:

- #731
- #732

**Comment by yamahige** [comment]
It's Okay, thanks for your investigation.

> This is not a simple task.

I totally agree! I'm struggling with lists these days, too.

**Comment by MurakamiShinyu** [comment]
I was able to make a quick fix. PR #1397.

Test: https://vivliostyle-git-fix-issue1391-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/yamahige/4e3e2bac575acc84fde84aeda5d711b9/raw/dcd73500606634a5aacf25ac8845852928a85b47/list-item-counter.html

Screenshot:
![Screenshot 2024-10-18 15 12 45](https://github.com/user-attachments/assets/9d17b890-bb66-4650-a175-df5ecfcc043e)
