### ISSUE TITLE
Bug: Right-floating image appears twice

### ISSUE THREAD

**Issue by depth42** [vivliostyle/vivliostyle.js#1422]
**Describe the bug**
When an image is contained in a div that is set to float:right, the image may be paginted simultaneously onto two pages.

**To Reproduce**
Paginate the attached document with the latest version of Vivliostyle.

**Expected behavior**
The image should only appear on the second page, but it appears on the first AND on the second page.

**Screenshots**
<img width="1316" alt="screenshot" src="https://github.com/user-attachments/assets/e751d17a-91b3-4a3e-97c5-92592017d41c">

**Desktop :**
 - macOS 15.1.
 - Safari 18.1

[FloatingImageBug.zip](https://github.com/user-attachments/files/17832889/FloatingImageBug.zip)

**Comment by MurakamiShinyu** [comment]
Thank you for your report. I found that the issue was introduced by the fix for issue #1383 (PR #1384). I will investigate the problem and fix it.

**Comment by MurakamiShinyu** [comment]
Fixed in #1423.

Test:
- Before fix (v2.30.6): https://vivliostyle.github.io/viewer/v2.30.6/#src=https://gist.githubusercontent.com/MurakamiShinyu/d4606ae87bcdd18c86b7f31afc57fd2f/raw/issue1422test1.html
- After fix: https://vivliostyle-git-fix-issue1422-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/d4606ae87bcdd18c86b7f31afc57fd2f/raw/issue1422test1.html

**Comment by depth42** [comment]
Thank you for the rapid fix! It's working fine now.
