### ISSUE TITLE
Add support for CSS Masking Module Level 1

### ISSUE THREAD

**Issue by frivoal** [vivliostyle/vivliostyle.js#150]
https://drafts.fxtf.org/css-masking-1/

This is a big spec with lots of properties, but as far as I can tell without having reviewed it in detail, it does not affect layout, so we should be able to delegate it to the browser.

**Comment by kwkbtr** [comment]
Support for [`clip-path`](https://drafts.fxtf.org/css-masking-1/#propdef-clip-path) and [`clip-rule`](https://drafts.fxtf.org/css-masking-1/#propdef-clip-rule) is added in #296.
Since `mask-*` properties do not work on some browsers, only [`mask` property defined in SVG 1.1](https://www.w3.org/TR/SVG11/masking.html#MaskProperty) is supported for now.

**Comment by MurakamiShinyu** [comment]
I close this issue since already implemented basically.
