### ISSUE TITLE
Different display sizes produce different page sizes in Chrome

### ISSUE THREAD

**Issue by tofi86** [vivliostyle/vivliostyle.js#235]
Default PDF output size in my Chrome browser is A4.

When printing a PDF of the Apollo sample on in Chrome on my external Thunderbolt Display (2560x1440) the PDF size is 243,1x302,3mm (not A4(!)).

When printing the same sample on my 13,3" MacBook Pro (Display resolution 1280 x 800, native retina 2560 x 1600) the PDF page dimensions are 169x176mm

I would expect them to be A4? or at least be the same proportions regardless of which display size is used...

**Comment by kwkbtr** [comment]
Sorry for the late response.
Vivliostyle.js uses the current window size (excluding the top bar) as the page size of PDF output when no page size (or `auto`) is specified with CSS, since I think it is good to be able to get a PDF with the same layout as you see on screen.
If you want a A4 PDF, you can set the page size to A4 in a drop down menu, which appears when you click the Vivliostyle logo at the top right corner of the window.
Does that solve your problem?

**Comment by tofi86** [comment]
Oh gosh, I didn't even know about the existance of this menu! :scream:
Sorry for bothering you with that. For sure it works fine when setting the page size there and `auto` makes sense as well!

I'm closing this issue...

**Comment by tofi86** [comment]
> Oh gosh, I didn't even know about the existance of this menu! :scream:

Probably you can change the icon to a "gear icon" or such so that it's more obvious... ;-)

**Comment by kwkbtr** [comment]
> Probably you can change the icon to a "gear icon" or such so that it's more obvious... ;-)

Thank you for the feedback! We will think about it.
