### ISSUE TITLE
How to style the image to fill one page column without cropping

### ISSUE THREAD

**Issue by Leminkainen** [vivliostyle/vivliostyle.js#349]
Hi,

I have been struggling with this problem for a while. I need one image to completely fill a single page column (i.e. left or right page) without cropping. It should be responsive. Its size will vary, but it should always keep its proportions. I tried a lot of different css options with no luck.

I hoped something like the css below would work, but it seems to fail to get the height (max-height ) property of the page column, so it crops on height:

`img { max-width:100%; max-height:100%; margin:auto; }`

Any help greatly appreciated!

**Comment by julientaq** [comment]
what happens if you put your image inside a figure tag? This way you’ll use the image as a background image with a `background-size:cover`.
and you may also need to produce a pagemaster for this specific point. If you have some code somewhere to look at it, i’ll be happy to help.

**Comment by MurakamiShinyu** [comment]
One possible solution would be specifying `height: 100%` on containing blocks of the image. For example,

```css
html, body {
  margin: 0;
  height: 100%;
}
body > img {
  display: block;
  max-width: 100%;
  max-height: 100%;
  margin: auto;
}
```

This works because the height of the containing block of the image is specified explicitly by `height: 100%` and the percentage value of the image's `max-height: 100%` can be resolved.
(CSS spec says: ["If the height of the containing block is not specified explicitly (...), the percentage value is treated as (...) 'none' (for 'max-height')."](https://drafts.csswg.org/css2/visudet.html#propdef-max-height))

Unfortunately, this might not be very useful, because it is necessary to specify `height: 100%` to all ancestor elements of the image with `max-height: 100%`. This will be solved if we can use the [viewport-percentage lengths](https://www.w3.org/TR/css3-values/#viewport-relative-lengths) such as `vw` and `vh`, e.g.,

```css
  max-width: 100vw;
  max-height: 100vh;
```

Currently, these units do not work properly on vivliostyle (sorry), but we are going to fix this problem.

**Comment by Leminkainen** [comment]
Thank you for the height solution, Murakami-san! It's working like a charm. Loving Vivliostyle so far! :)
