### ISSUE TITLE
Tables on fiduswriter

### ISSUE THREAD

**Issue by regostar** [vivliostyle/vivliostyle.js#463]
The table in fiduswriter generated pdf is not uniform. The columns get misaligned after a few rows.
Here is an example :- 

![table](https://user-images.githubusercontent.com/26195098/48752647-589ec700-ecb0-11e8-964b-9505ef845aaf.png)

If you notice the last two rows have content exactly same as the ones above it, but there is a misalignment of the columns belonging to the last 2 rows.

I have tested the latest fiduswriter after integration with vivliostyle.
[fiduswriter GitHUb](https://github.com/fiduswriter/fiduswriter) develop branch and document-templates branch.

**Comment by spring-raining** [comment]
Hello regostar, thank you for reporting the issue!

That example seems to be created by Fiduswriter, therefore we cannot find that the cause of this problem is whether Vivliostyle or Fiduswriter. Could you show me an HTML source of minimal reproducible example? (Fiduswriter can export HTML sources by selecting `Export > HTML`)

**Comment by regostar** [comment]
This might not be a bug, it just has something to do with the formatting of the predecessor row inherited into the current row. This occurs when I have two tables with the same content, one having a title row extra with characters in bold, the other not having that.

[table-test.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/2602727/table-test.html.zip)

I think its a small formatting issue with fiduswriter (or might not be an issue at all), you may close this issue if you feel so.

**Comment by spring-raining** [comment]
Ah, ok I checked the HTML file.

<details>
<summary>table-test.html</summary>

```html
...omitted...
<table>
  <tbody>
    <tr>
      <td>
        <p><strong>M</strong></p>
      </td>
      <td>
        <p><strong>Destination</strong></p>
      </td>
      <td>
        <p><strong>Objective</strong></p>
      </td>
      <td>
        <p><strong>Number</strong></p>
      </td>
      <td>
        <p><strong>Money</strong></p>
      </td>
      <td>
        <p><strong>Time</strong></p>
      </td>
    </tr>
    <tr>
      <td>
        <p>M4</p>
      </td>
      <td>
        <p>opportunity due to several reasons. Rise in incidence of post-surgicaL</p>
      </td>
      <td>
        <p>Such systems also have an enormous impact on patients’ quality of life.</p>
      </td>
      <td>
        <p>9</p>
      </td>
      <td>
        <p>500k</p>
      </td>
      <td>
        <p>Apr 2018</p>
      </td>
    </tr>
  </tbody>
</table>
<table>
  <tbody>
    <tr>
      <td>
        <p>M4</p>
      </td>
      <td>
        <p>opportunity due to several reasons. Rise in incidence of post-surgicaL</p>
      </td>
      <td>
        <p>Such systems also have an enormous impact on patients’ quality of life.</p>
      </td>
      <td>
        <p>9</p>
      </td>
      <td>
        <p>500k</p>
      </td>
      <td>
        <p>Apr 2018</p>
      </td>
    </tr>
  </tbody>
</table>
...omitted...
```
</details>

---

As you might expect, the width length of rows is different between the two tables. Because of an appearance consistency, the width of HTML tables is calculated from ***all*** cell contents of that table, which includes the other rows. I suppose the solution to this problem is that including all rows in only one table.

**Comment by regostar** [comment]
Yes I agree
