### ISSUE TITLE
Images in Table on Fiduswriter

### ISSUE THREAD

**Issue by regostar** [vivliostyle/vivliostyle.js#464]
When I insert an image in a table on fiduswriter and generate a pdf, the output is not satisfactory. I noticed 3 bugs.

- The sizes of images are not uniform

- Margins of images overlap

- Image cut abruptly 

This example will give a better idea :- 

![images](https://user-images.githubusercontent.com/26195098/48752899-905a3e80-ecb1-11e8-8f57-2ed0498ffccd.png)

**Comment by MurakamiShinyu** [comment]
We can't reproduce the problems without the source HTML data. Please attach the source data (in Fidus Writer,  `Export > HTML`).

**Comment by regostar** [comment]
Sorry about that. Here is the source HTML data
[image not proper.html.zip](https://github.com/vivliostyle/vivliostyle.js/files/2610585/image.not.proper.html.zip)

**Comment by MurakamiShinyu** [comment]
I found the following problems in your HTML and CSS code:

### The sizes of images are not uniform

This is a source HTML problem. The table row containing the images is only a part of large table, and each table column width is determined by whole table content. Therefor, table column widths differ and the sizes of images are affected. 

If you split the table so that the table of images just contains images and short labels/captions, the sizes of images will be uniform.

### Margins of images overlap

It seems that there is a problem in the CSS, `figure {...}` rule in the fiduswriter's document.css, 
https://github.com/fiduswriter/fiduswriter/blob/b4fa8e352c843e0c5c639e2864903ce159153466/document/static/css/document.css#L93-L101

The problem is that the sum of `width: 80%`, `margin-left: 10%`, `margin-right: 10%`, `padding-left: 5px`, `padding-right: 5px`, `border-left-width: 1px` and `border-right-width: 1px` exceeds 100%, and this causes overflow from the table cell width.

### Image cut abruptly

I found that `-webkit-region-break-inside: avoid;` is specified in the `figure {...}` rule, but this nonstandard property does not work with Vivliostyle. The appropriate property to avoid breaks within the box is `break-inside: avoid`.

**Comment by regostar** [comment]
Many thanks :) 
I will try out the changes, test again and let you know ;)

**Comment by regostar** [comment]
The solutions for Margins of images overlap, Image cut abruptly were successfully implemented and tested. It has also been merged with fiduswriter repo. I thank you for that.
For the issue of image sizes, I hope that the next version of fiduswriter would not calculate the table - column widths using the text length.
