### ISSUE TITLE
"counter-reset: page;"  doesn't work properly with web publications

### ISSUE THREAD

**Issue by butameron** [vivliostyle/vivliostyle.js#522]
I want to exclude book cover pages from page counter.
To do this, I tried to use web publications json and set `@page :first { reset-counter: page; }` to second document, because vivliostyle doesn't support named pages. however this doesn't work as I expected.

## Steps to Reproduce 
Open  Vivliostyle with `#x=http://url/to/testbook.json`:

testbook.json
```
{
    "@context": [
        "https://schema.org",
        "https://www.w3.org/ns/wp-context"
    ],
    "type": "Book",
    "dateModified": "",
    "readingOrder": [
        "./test.html",
        "./test2.html"
    ]
}
```

test.html
```
<html>
    <head>
        <style>
            @page {
                size: A4;
                            
                @top-left {
                    content: counter(page);
                }

            }
            div { page-break-after: always; }
        </style>
    </head>
    <body>
        <div>
            A
        </div>
        <div>
            B
        </div>
    </body>
</html>
```

test2.html
```
<html>
    <head>
        <style>
            @page {
                size: A4;
                            
                @top-left {
                    content: counter(page);
                }

            }
            @page :first {
                counter-reset: page;
            }

            div { page-break-after: always; }
        </style>
    </head>
    <body>
        <div>
            C
        </div>
        <div>
            D
        </div>
    </body>
</html>
```

## Expected result
Page A: page counter value = 1
Page B: page counter value = 2
Page C: page counter value = 1
Page D: page counter value = 2

## Actual result
Page A: page counter value = 1
Page B: page counter value = 2
Page C: page counter value = 3
Page D: page counter value = 4

**Comment by spring-raining** [comment]
Thank you for the reporting! The `page` seems to be a counter of entire of a book so that it's may not acceptable for describing a document-wise page counter. In an environment of Vivliostyle, by defining the new counter which likes below works fine:

#### test2.html

```html
<html>
    <head>
        <style>
            @page {
                size: A4;
                counter-increment: doc-page;
                @top-left {
                    content: counter(doc-page);
                }
            }
            body {
                counter-reset: doc-page;
            }
            div { page-break-after: always; }
        </style>
    </head>
    <body>
        <div>
            C
        </div>
        <div>
            D
        </div>
    </body>
</html>
```

Hoping this answer your question.

**Comment by MurakamiShinyu** [comment]
Thanks @butameron for reporting the issue and @spring-raining for giving us a good workaround. 

There are some problems on [CSS Paged Media](https://drafts.csswg.org/css-page/) spec and Vivliostyle.js implementation.

In the spec, [First-page pseudo-class: `:first`](https://drafts.csswg.org/css-page/#first-pseudo) is defined as

> The `:first` pseudo-class matches the first printed page of a document.

However, this spec is not very clear, when the document is a web publication, whether the `:first` matches only the first page of the web publication or matches first page of each sub-document (HTML) in the web publication.

Also it is not clear whether the [Page-based counters](https://drafts.csswg.org/css-page/#page-based-counters) are for a whole web publication or for each sub-document in the web publication.

(The problem is that the CSS Paged Media specification is not considered for publications composed of multiple HTML documents.)

In the Vivliostyle.js implementation, the `:first` matches only the first page of the web publication, and the page-based counters count consecutive pages in a whole web publication. Therefore, the `page` counter is not reset at the first page of the second document even when `@page :first { reset-counter: page; }` is specified.

**Comment by butameron** [comment]
@spring-raining Thank you. It works

**Comment by MurakamiShinyu** [comment]
Now, [Vivliostyle.js v2.5.0](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#250-2021-02-26) supports the [`:nth()` page selector](https://drafts.csswg.org/css-gcpm-3/#document-page-selectors).

See [#700 feat(core): Support the :nth() page selector](https://github.com/vivliostyle/vivliostyle.js/pull/700)

> * In multi-document publications, the `:nth(1)` matches the first page of each document,
>   but the `:first` matches only the first page of the first document.
>   (see: https://github.com/vivliostyle/vivliostyle.js/issues/667#issuecomment-738020563 )

You can use `@page :nth(1) { counter-reset: page; }` to reset the page counter at each or a specific document in web publications (multi-document publications).

Tests:
https://raw.githack.com/vivliostyle/vivliostyle.js/master/packages/core/test/files/index.html#Nth_page_selector

(source: https://github.com/vivliostyle/vivliostyle.js/tree/master/packages/core/test/files/nth-page)

I believe this issue is now resolved.
