### ISSUE TITLE
Incorrect behavior of ::first-letter selector

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#566]
Example:

``` html
<style>
    p::first-letter {
        color: blue;
    }
</style>
<p>abcde</p>
<p>あいうえお</p>
```

For the first paragraph, only 'a' is blue as expected.
For the second paragraph, however, the whole paragraph becomes blue incorrectly.

**Comment by MurakamiShinyu** [comment]
The first problem, "…the whole paragraph becomes blue incorrectly", was fixed in PR #680 ([v2.4.0](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#240-2020-12-28)) by updating the [firstLetterPattern](https://github.com/vivliostyle/vivliostyle.js/blob/e02a06c2bb7400e61e5c956aef90b31004ad2685/packages/core/src/vivliostyle/base.ts#L28).

The second problem, "when `::first-letter` is used alone or with the universal selector", remains.
