### ISSUE TITLE
Root element styles are not inherited to page context

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#568]
Spec: [CSS Paged Media 3 - 6. Page Properties](https://drafts.csswg.org/css-page/#page-properties)

> The page context inherits from the root element.

**Comment by MurakamiShinyu** [comment]
Fixed in #775 

Test with Vivliostyle Viewer:

- After this fix:
  - https://vivliostyle.vercel.app/#src=https://gist.githack.com/MurakamiShinyu/87b6f138d2fc40914e2f042f25ecc3de/raw/root-style-inherit-at-page.html  
    (Gist: https://gist.github.com/MurakamiShinyu/87b6f138d2fc40914e2f042f25ecc3de)
  - https://vivliostyle.vercel.app/#src=https://github.com/baldurbjarnason/vivliostyle-tests/blob/main/vivliostyle-test-italics.html  
    (Thanks @baldurbjarnason for providing this test: [vivliostyle-test-custompage.html](https://github.com/baldurbjarnason/vivliostyle-tests/blob/main/vivliostyle-test-custompage.html))
- Before this fix:
  - https://vivliostyle.github.io/viewer/v2.9.1/#src=https://gist.githack.com/MurakamiShinyu/87b6f138d2fc40914e2f042f25ecc3de/raw/root-style-inherit-at-page.html
  - https://vivliostyle.github.io/viewer/v2.9.1/#src=https://github.com/baldurbjarnason/vivliostyle-tests/blob/main/vivliostyle-test-italics.html
