### ISSUE TITLE
Hide MathJax status message on print

### ISSUE THREAD

**Issue by kwkbtr** [vivliostyle/vivliostyle.js#66]
"Typesetting math: 100%"

**Comment by pkra** [comment]
Just a not from the MathJax team. See http://docs.mathjax.org/en/latest/options/hub.html -- just configure MathJax to use `showProcessingMessages: false, messageStyle: "none"`.

From a quick look it seems like MathJax is used very inefficiently, i.e., vivliostyle is queuing equations individually instead of in batches; this prevents most of the performance optimizations built into MathJax.

**Comment by kwkbtr** [comment]
@pkra
Thank you for your comment!
I added a new issue to fix Vivliostyle.js to use MathJax more efficiently: #68.
