### ISSUE TITLE
wrong indent of 「」bracket at first line in second page 

### ISSUE THREAD

**Issue by butameron** [vivliostyle/vivliostyle.js#861]
**Describe the bug**

縦書きの原稿で

「ああああ」
「ああああ」
「ああああ」

というように、改行による会話文が連続する場合、2ページ目の最初の行のインデントが小さくなり、行頭が不揃いになります。

**To Reproduce**

以下のHTMLをVivliostyleでレンダリングします
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <style>
        @page {
            size: A5;
        }
        html {
            font-family: "源ノ明朝";
        }
        body {
            writing-mode: vertical-rl;
            line-height: 2;
        }
    </style>
</head>
<body>
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
    「あああああああ」<br />
</body>
</html>
```

※横書き原稿では試していません。

**Expected behavior**

行頭が揃う。

**Screenshots**

2ページ目の最初の行頭のインデントだけが小さくなっている。

![image](https://user-images.githubusercontent.com/19877154/152715199-a634d92a-4ff2-4351-a38a-b5860160457b.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 97.0.4692.99（Official Build） （64 ビット）

**Comment by MurakamiShinyu** [comment]
不具合確認しました。

- [Vivliostyle Viewerでテスト](https://vivliostyle.vercel.app/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%3E%20%3Chead%3E%20%20%20%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20%20%20@page%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20size:%20A5;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20html%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20font-family:%20%22%E6%BA%90%E3%83%8E%E6%98%8E%E6%9C%9D%22;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20body%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20writing-mode:%20vertical-rl;%20%20%20%20%20%20%20%20%20%20%20%20%20line-height:%202;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%3C/style%3E%20%3C/head%3E%20%3Cbody%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%3C/body%3E%20%3C/html%3E)


`<br>` タグで改行をしていると、そこで改ページが起きたときの行頭が、強制改行ではなくて折り返し行頭と同じ扱いになってしまい、デフォルトのtext-spacingで折り返し行頭には `trim-start` が効くので半角幅になるというバグのようです。

なるべく早く修正したいと思いますが、それまで、このバグを回避するには、`<br>` タグではなくて `<p>` を使うとよいです：

- [`<p>` を使った場合のテスト](https://vivliostyle.vercel.app/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%3E%20%3Chead%3E%20%20%20%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20%20%20@page%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20size:%20A5;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20html%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20font-family:%20%22%E6%BA%90%E3%83%8E%E6%98%8E%E6%9C%9D%22;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20body%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20writing-mode:%20vertical-rl;%20%20%20%20%20%20%20%20%20%20%20%20%20line-height:%202;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20p%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20margin:%200;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%3C/style%3E%20%3C/head%3E%20%3Cbody%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%20%20%20%20%3Cp%3E%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3C/p%3E%20%3C/body%3E%20%3C/html%3E)

**Comment by butameron** [comment]
ありがとうございます

**Comment by MurakamiShinyu** [comment]
Fixed in #864

- [Test with Vivliostyle Viewer](https://vivliostyle-git-fix-issue861-vivliostyle.vercel.app/#src=data:,%3C!DOCTYPE%20html%3E%20%3Chtml%3E%20%3Chead%3E%20%20%20%20%20%3Cmeta%20charset=%22utf-8%22%20/%3E%20%20%20%20%20%3Cstyle%3E%20%20%20%20%20%20%20%20%20@page%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20size:%20A5;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20html%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20font-family:%20%22%E6%BA%90%E3%83%8E%E6%98%8E%E6%9C%9D%22;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%20%20%20%20body%20%7B%20%20%20%20%20%20%20%20%20%20%20%20%20writing-mode:%20vertical-rl;%20%20%20%20%20%20%20%20%20%20%20%20%20line-height:%202;%20%20%20%20%20%20%20%20%20%7D%20%20%20%20%20%3C/style%3E%20%3C/head%3E%20%3Cbody%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%20%20%20%20%E3%80%8C%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%81%82%E3%80%8D%3Cbr%20/%3E%20%3C/body%3E%20%3C/html%3E)
