### ISSUE TITLE
Question: script support

### ISSUE THREAD

**Issue by Iacobus1983** [vivliostyle/vivliostyle.js#918]
I've tried to typeset with vivliostyle an html document which uses [jquery-textfill](https://jquery-textfill.github.io/) script to dynamically resize text so that it fits in a box. I've tried with another script too, [fittext](https://github.com/davatron5000/FitText.js). Neither worked. 

As a piece of additional information: with pagedjs-cli it worked (but unfortunately it doesn't support other features which vivliostyle provides).

I'm not a developer myself, so I've no idea if it depends on vivliostyle specific architecture, and if there's some path towards a solution.

Please do not hesitate to close the issue if it's not relevant. Thanks in advance.

**Comment by MurakamiShinyu** [comment]
Vivliostyle.js supports JavaScript in HTML documents since [Vivliostyle.js v2.13.0](https://github.com/vivliostyle/vivliostyle.js/blob/master/CHANGELOG.md#2130-2022-01-17). See:

- https://github.com/vivliostyle/vivliostyle.js/pull/824

However, this doesn't mean any scripts work as expected, because the DOM structure that generated by Vivliostyle's layout processing differs from the original HTML document.

I tested the example of jquery-textfill: https://jquery-textfill.github.io/example/
with Vivliostyle Viewer:
https://vivliostyle.vercel.app/#src=https://jquery-textfill.github.io/example/

It seems to be working (screenshot):
![Screen Shot 2022-05-07 at 18 04 11](https://user-images.githubusercontent.com/3324737/167247417-3ef9abd8-71b4-4206-a1ef-fa76a93d9c83.png)

However, I found that when I reduced the page size so that this document spans two pages, it will only work on the first page.

**Comment by Iacobus1983** [comment]
Wonderful information, thank you very much!
