### ISSUE TITLE
An issue with drop-caps

### ISSUE THREAD

**Issue by Iacobus1983** [vivliostyle/vivliostyle.js#923]
I'm creating pdf with drop-caps at the beginning of the first paragraph using `p:first-of-type::first-letter`:
![image](https://user-images.githubusercontent.com/77020754/168841041-0d5a3fa1-1e32-4b21-ad53-44be852062ac.png)
However, if the first paragraph is too long to be typeset only on the first page, I get this:
![image](https://user-images.githubusercontent.com/77020754/168841363-f1f8b860-3da0-4fef-83f5-411cfec56e45.png)

If I manually wrap the first letter in a `span class=dropcaps`, though, the letter is typeset correctly.

I have already had this problem in the past, then it seemed to be fixed with some version update (but I cannot be completely sure). Now I've just updated vivliostyle (core 2.15.1, cli 4.12.1; Chromium is 101.0.4950.0 (Build) (x86_64)), and the problem is there.

Here the full html+css of my example: [dropcaps.txt](https://github.com/vivliostyle/vivliostyle.js/files/8709364/dropcaps.txt)

**Comment by MurakamiShinyu** [comment]
Fixed in #928 

Test with Vivliostyle Viewer, before and after the fix:
- Before the fix (v2.15.1): https://vivliostyle.github.io/viewer/v2.15.1/#src=https://gist.githack.com/MurakamiShinyu/1b3bf033e027da3bcc6a25d34edcceda/raw/dropcaps.html
- After the fix (v2.15.2): https://vivliostyle.github.io/viewer/v2.15.2/#src=https://gist.githack.com/MurakamiShinyu/1b3bf033e027da3bcc6a25d34edcceda/raw/dropcaps.html

Thank you @Iacobus1983 for the bug report😃
