### ISSUE TITLE
cli v4.12.1 以降 pdf 出力時に版面が表示されなくなる

### ISSUE THREAD

**Issue by ozwis** [vivliostyle/vivliostyle.js#929]
## 概要
* cli v4.12.1 以降 pdf 出力時に版面の一部が表示されなくなってしまいました。  
  以下に、自分の手元で問題を再現した最小限のファイルと、実行したコマンドリストを記載します。
  
* 本文原稿(md) + css + vivliostyle.config.js
  [cli4_12_1_test.zip](https://github.com/vivliostyle/vivliostyle-cli/files/8762121/cli4_12_1_test.zip)

* pdf 出力前のディレクトリ
  ```
   .
   ├── fonts
   │   └── ShipporiMincho-Regular.otf
   ├── node_modules
   ├── honbun.md
   ├── layout_body.css
   ├── package.json
   ├── package-lock.json
   ├── publication.json
   └── vivliostyle.config.js
   ```

* 実行したコマンド
   ```
   $ npm install @vivliostyle/cli@4.12.1
   
   added 398 packages, and audited 399 packages in 2s
   
   136 packages are looking for funding
     run `npm fund` for details
   
   4 high severity vulnerabilities
   
   To address all issues (including breaking changes), run:
     npm audit fix --force
   
   Run `npm audit` for details.
   
   $ npx vivliostyle -v
   cli: 4.12.1
   core: 2.15.1
   
   $ npx vivliostyle init
   Successfully created vivliostyle.config.js
   
   $ npx vivliostyle build -o output_4_12_1.pdf
   ℹ Rendering browser (Chromium) is not installed yet. Downloading now...
   ✔ Successfully downloaded browser
   ✔ honbun.md テスト
   ✔ honbun.md テスト
   ⊙ Building PDF
   output_4_12_1.pdf has been created.
   🎉 Built successfully.
   ```

* 出力結果 (cli v4.12.1)
  [output_4_12_1.pdf](https://github.com/vivliostyle/vivliostyle-cli/files/8762193/output_4_12_1.pdf)
 
* 上記出力を確認した後、次の手順で cli v4.12.0 にダウングレードすると、正常に版面が出力されます。

* 実行したコマンド
   ```
   $ npm remove @vivliostyle/cli
   $ npm install @vivliostyle/cli@4.12.0
   $ npx vivliostyle build -o output_4_12_0.pdf
   ```

* 出力結果 (v4.12.0)
  [output_4_12_0.pdf](https://github.com/vivliostyle/vivliostyle-cli/files/8762212/output_4_12_0.pdf)

**Comment by MurakamiShinyu** [comment]
@ozwis バグ報告ありがとうございます。

調べたところ vivliostyle.js 側の問題でしたので、issueをvivliostyle.jsのほうに移動しました。

スタイルシートの `@page {…}` に bleed の指定があり、marks （トンボ）の指定がない場合に、この問題が起きることが分かりました。

```
    bleed: 3mm;          /* 断ち切り3mm */
```
この行を削除するか、次のようにトンボの指定もするかすると、この問題は起きません。
```
    bleed: 3mm;          /* 断ち切り3mm */
    marks: crop cross;
```

**Comment by ozwis** [comment]
@MurakamiShinyu 対処方法ご教示いただきありがとうございます。  
トンボの指定をしまして、v4.12.1 でも版面が表示されること確認できました :bow:

**Comment by MurakamiShinyu** [comment]
Fixed in #930.

Test with Vivliostyle Viewer:
(Test sample: [「ごん狐」](https://github.com/vivliostyle/vivliostyle_doc/tree/gh-pages/samples/gon) with `@page { bleed: 3mm; }`)

- Before the fix (v2.15.2): https://vivliostyle.github.io/viewer/v2.15.2/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gon/index.html&userStyle=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0A@page%20%7B%0A%20%20bleed:%203mm;%0A%7D
  - ![Screen Shot 2022-05-25 at 16 30 38](https://user-images.githubusercontent.com/3324737/170206209-116133b0-fcd7-4ce0-acf9-b4b9019152ae.png)

- After the fix: https://vivliostyle-git-fix-issue929-vivliostyle.vercel.app/#src=https://vivliostyle.github.io/vivliostyle_doc/samples/gon/index.html&userStyle=data:,/*%3Cviewer%3E*/%0A/*%3C/viewer%3E*/%0A@page%20%7B%0A%20%20bleed:%203mm;%0A%7D
  - ![Screen Shot 2022-05-25 at 16 30 55](https://user-images.githubusercontent.com/3324737/170206384-75ca1320-8e1b-45c2-ac41-6a3581d490e8.png)
