### ISSUE TITLE
段間罫が版面からはみ出す（縦組み、段組み）

### ISSUE THREAD

**Issue by skmtjny** [vivliostyle/vivliostyle.js#978]
不具合の報告は日本語でも大丈夫でしょうか？

**Describe the bug**
 - 縦組みの段組みにおいて、段間罫を設定すると版面からはみ出して罫線が描画される
 - また、段間罫を設定した状態でPDFを作成（build）すると全体が縮小されたPDFができる

**To Reproduce**
- CSSで段組みおよび段間罫の設定を行い、vivliostyle/cliで読み込み（添付ファイル参照）
~~~
body {
  writing-mode: vertical-rl;
  text-orientation: upright;
  column-fill: auto;
  columns: 2;
  column-gap: 16pt;
  column-rule: solid 1px; /* 段間罫の指定 */
}
~~~

**Expected behavior**
 - 段間罫の描画が版面内に収まる

**Screenshots**
<img src="https://user-images.githubusercontent.com/1134887/185561914-a7cc7882-0246-4086-9fd3-c220f67c7b93.png" width="50%">

**Desktop**
 - OS: Windows 10 64 bit
 - Browser: Chromium 104.0.5112.48（Developer Build）（64 bit）
 - cli: 5.5.1
 - core: 2.17.1

[two-columns-test.zip](https://github.com/vivliostyle/vivliostyle.js/files/9379826/two-columns-test.zip)

**Comment by MurakamiShinyu** [comment]
@skmtjny バグ報告ありがとうございます！　不具合確認しました。
次のバージョンで修正します。

**Comment by MurakamiShinyu** [comment]
Fixed in #982 

Test sample: https://gist.githubusercontent.com/MurakamiShinyu/29ee5b22a5a799f2558fe42b2a17e0ec/raw/column-rule-vertical.html

Test with Vivliostyle Viewer:
- before this fix: https://vivliostyle.github.io/viewer/v2.17.2/#src=https://gist.githubusercontent.com/MurakamiShinyu/29ee5b22a5a799f2558fe42b2a17e0ec/raw/column-rule-vertical.html
  - result screenshot: 
![Screen Shot 2022-09-02 at 16 25 48](https://user-images.githubusercontent.com/3324737/188082767-5da43107-8dea-4fbb-b412-9b9b21181377.png)

- after this fix: https://vivliostyle-git-fix-issue978-vivliostyle.vercel.app/#src=https://gist.githubusercontent.com/MurakamiShinyu/29ee5b22a5a799f2558fe42b2a17e0ec/raw/column-rule-vertical.html
  - result screenshot: 
![Screen Shot 2022-09-02 at 16 27 39](https://user-images.githubusercontent.com/3324737/188082799-c2d9c3cd-6fb1-4b55-8e41-7036b29b42fe.png)

**Comment by skmtjny** [comment]
@MurakamiShinyu 
早急なご対応ありがとうございます！
